### ISSUE TITLE
Raising Events

### ISSUE THREAD

**Issue by sicollins** [jagdeepsingh91/angularMultipleSelect#16]
Great little plugin works fantastically!

A great addition to this would be assigning some kind of callback to the directive which is called when the onSuggestedItemsClick() event is raised.

In my case I want to do additional work each time my ng-model passed to the directive changes.

Have you thought about making this into a .component() also?

**Comment by jagdeepsingh91** [comment]
Thanks sicollins for feedback.

I have already developed 3 major callback addition to this plugin & would be releasing new version in couple of days. In new release you will get follow things : 

1. beforeAddItem : type - function, which will be called just before user select/add an item to ng-model.
2. afterAddItem : type - function, which will be called after user add an item to ng-model.
3. beforeRemoveItem : type - function, which will be called just before user delete/remove an item from ng-model.
4. afterRemoveItem : type - function, which will be called after user delete/remove an item from ng-model.

Apart from these, if you need any more functionality then please let me know.

Thanks

**Comment by sicollins** [comment]
Great work! Fantastic - will update when you release.

**Comment by jagdeepsingh91** [comment]
Hi,

I have added event listeners, you can find its docs on readme/home page.
So, i am closing this issue. If you still need anything you can raise issue and for more ideas & suggestion you are most welcome.
