### ISSUE TITLE
What is the license for this software

### ISSUE THREAD

**Issue by fw060** [jagdeepsingh91/angularMultipleSelect#17]
Hi,
We like this plugin but want to make sure we can use it. What is the license for this software? 

Thanks,
Fei

**Comment by fw060** [comment]
Sorry, I forget to check the LICENSE file, so it is MIT license. If you can update the git web page, that will be great! 

Thanks again for the great work!

**Comment by jagdeepsingh91** [comment]
Hi,

I have added MIT LICENSE in readme.md file also. So, its totally free.
And added more functionality of event listeners.
You can check it out.
