### ISSUE TITLE
Please provide suggestion array list or url???

### ISSUE THREAD

**Issue by cianochannel** [jagdeepsingh91/angularMultipleSelect#27]
Hi, really a good work with multiple autocomplete select, but when i try it on my project console returns
*******Angular-multiple-select **** ----- Please provide suggestion array list or url**

In my HTML
<multiple-autocomplete 
                       ng-model="retList"
                          object-property="name"
                          suggestions-arr="optionsList">
                        </multiple-autocomplete>

In my Controller in JS
$scope.optionsList = [
          {id: 1,  name : "Java"},
          {id: 2,  name : "C"},
          {id: 3,  name : "C++"},
          {id: 4,  name : "AngularJs"},
          {id: 5,  name : "JavaScript"}
        ];

What would be wrong? Thanks

**Comment by cianochannel** [comment]
Ehm...sorry...it works fine
Really Thank you

**Comment by jagdeepsingh91** [comment]
Thanks. So i am closing this issue. If you still have any issue please open new one. Thanks :)
