### ISSUE TITLE
Validate bower.json

### ISSUE THREAD

**Issue by andreicioromila** [jagdeepsingh91/angularMultipleSelect#7]
Hi,

I have downloaded you package through bower and I am encountering some issues with the dependency to angular. There is a **bower.json** which lists **angular** as a dependency, and there's also a **.bower.json** (notice the . in front) that lists **angularjs**. Now, when doing bower install, I have both angular (from my project's dependencies) and angularjs (which was probably found in the .bower.json file)
Could you take a look into why is angularjs listed as a dependency instead of angular?

Thanks for looking into this,
Andrei

**Comment by jagdeepsingh91** [comment]
Hi @andreicioromila ,

Thanks for notifying me.
The issue you have raised was conflicting of name between angular & angularjs as a dependencies. Anyway i have fixed that too. 

And i have added more functionality, check it out here https://github.com/jagdeepsingh91/angularMultipleSelect

Thanks for your support.
